name: SYNC-REPO-tmp

on:
  push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      env:
        SOURCE_REPO: "cnrancher/${{ GITHUB_REF##*/  }}"
        SOURCE_BRANCH: "refs/remotes/source/${{ GITHUB_REF##*/ }}"
        DESTINATION_REPO: "kingsd041/${{ GITHUB_REPOSITORY##*/ }}"
        DESTINATION_BRANCH: "refs/heads/${{ GITHUB_REPOSITORY##*/ }}"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo SOURCE_REPO: ${SOURCE_REPO}
        echo SOURCE_BRANCH: ${SOURCE_BRANCH}
        echo DESTINATION_REPO: ${DESTINATION_REPO}
        echo DESTINATION_BRANCH:  ${DESTINATION_BRANCH}