name: SYNC-REPO-tmp

on:
  push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
      BRANCH_NAME: ${{ github.ref_name	}}
    steps:
    - name: 
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: repo-sync
      env:
        SOURCE_REPO: "cnrancher/${{ env.REPO_NAME }}"
        SOURCE_BRANCH: "refs/remotes/source/${{ env.BRANCH_NAME }}"
        DESTINATION_REPO: "kingsd041/${{ env.REPO_NAME }}"
        DESTINATION_BRANCH: "refs/heads/${{ env.BRANCH_NAME }}"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo SOURCE_REPO: ${SOURCE_REPO}
        echo SOURCE_BRANCH: ${SOURCE_BRANCH}
        echo DESTINATION_REPO: ${DESTINATION_REPO}
        echo DESTINATION_BRANCH:  ${DESTINATION_BRANCH}
        echo GITHUB_REF: ${GITHUB_REF##*/}
        echo branch is: ${{ steps.extract_branch.outputs.branch }}