name: SYNC-REPO-2.5

on:
  push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: actions/checkout@v2
    - name: echo github env
      run: |
        echo ${{ steps.extract_branch.outputs.branch }}
    - name: echo github env2
      run: |
        echo running on branch ${GITHUB_REF##*/}
    - name: echo github env3
      run: |
        echo running on branch ${GITHUB_REF}
    - name: echo github env4
      run: |
        echo running on branch ${GITHUB_REF_NAME}
        echo GITHUB_HEAD_REF:  ${GITHUB_HEAD_REF}
        echo GITHUB_BASE_REF: ${GITHUB_BASE_REF}
        echo GITHUB_REF: ${GITHUB_REF}
        echo GITHUB_REF_PROTECTED: ${GITHUB_REF_PROTECTED}
        echo GITHUB_REF_TYPE: ${GITHUB_REF_TYPE}

#    - name: repo-sync
#      uses: cnrancher/git-sync@rancher/v2.0
#      env:
#        SOURCE_REPO: "cnrancher/pandaria-ui"
#        SOURCE_BRANCH: "refs/remotes/source/2.5-fixes-cn"
#        DESTINATION_REPO: "ranchervip/pandaria-ui"
#        DESTINATION_BRANCH: "refs/heads/2.5-fixes-cn"
#        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#      with:
#        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
