name: ttt-${{ GITHUB_REF_NAME }}
on:
  push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: echo github env2
      run: |
        echo running on branch ${GITHUB_REF##*/}
    - name: echo github env3
      run: |
        echo running on branch ${GITHUB_REF}
        echo GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
        echo github.sha ${{ github.sha }} 
        echo github.event.repository.name: ${{ github.event.repository.name }}
        echo GITHUB_REF_NAME: ${{ GITHUB_REF_NAME }}


#    - name: repo-sync
#      uses: cnrancher/git-sync@rancher/v2.0
#      env:
#        SOURCE_REPO: "cnrancher/pandaria-ui"
#        SOURCE_BRANCH: "refs/remotes/source/2.5-fixes-cn"
#        DESTINATION_REPO: "ranchervip/pandaria-ui"
#        DESTINATION_BRANCH: "refs/heads/2.5-fixes-cn"
#        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#      with:
#        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
