name: SYNC-REPO-tmp

on:
  push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: 
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: repo-sync
      env:
        SOURCE_REPO: "cnrancher/${{ github.event.repository.name }}"
        SOURCE_BRANCH: "refs/remotes/source/${{ steps.extract_branch.outputs.branch }}"
        DESTINATION_REPO: "kingsd041/${{ github.event.repository.name }}"
        DESTINATION_BRANCH: "refs/heads/${{ steps.extract_branch.outputs.branch }}"
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo SOURCE_REPO: ${SOURCE_REPO}
        echo SOURCE_BRANCH: ${SOURCE_BRANCH}
        echo DESTINATION_REPO: ${DESTINATION_REPO}
        echo DESTINATION_BRANCH:  ${DESTINATION_BRANCH}
        echo GITHUB_REF: ${GITHUB_REF##*/}
        echo branch is: ${{ steps.extract_branch.outputs.branch }}
        echo github.event.repository.name: ${{ github.event.repository.name }}
        echo github.ref_type	: ${{ github.ref_type	 }}